### ISSUE TITLE
how to connect it to a floppy

### ISSUE THREAD

**Issue by youxiaojie** [majbthrd/USBfloppy#1]
how to connect it to a floppy?can you port it to arduino?

**Comment by majbthrd** [comment]
This code is the foundation for a virtual floppy; there is no perceived need to duplicate functionality that can already be found in USB floppy products already for sale.  If, however, you do want to build on top of the code to interface to a salvage floppy drive, you will need to do this task by yourself.

There is no interest whatsoever in an Arduino port because the nature of Arduino users is to just ask lots of "how to" questions on wiring their Arduino PCB to other devices; this just foists the work and burden onto the open source author and I just don't have the time or patience for this.
